// <auto-generated />
using System;
using BettingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BettingAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231110232017_Seeder for 20 matches")]
    partial class Seederfor20matches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BettingAPI.Models.Match", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MatchTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<string>("TeamA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            ID = new Guid("1c2d829b-574b-4018-a013-2e495961e5af"),
                            Description = "OSFP - PAO",
                            MatchDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 1,
                            TeamA = "OSFP",
                            TeamB = "PAO"
                        },
                        new
                        {
                            ID = new Guid("d41a1476-7915-4787-96b0-cd1554897e8e"),
                            Description = "OSFP - PAO",
                            MatchDate = new DateTime(2023, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "OSFP",
                            TeamB = "PAO"
                        },
                        new
                        {
                            ID = new Guid("a1ed0b7f-bd55-47e3-ac8f-a9cfc084f493"),
                            Description = "AEK - ARIS",
                            MatchDate = new DateTime(2023, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 3, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "AEK",
                            TeamB = "ARIS"
                        },
                        new
                        {
                            ID = new Guid("e407ae90-843c-4221-8bcc-4e1174f55d7b"),
                            Description = "AEL - OFI",
                            MatchDate = new DateTime(2023, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 4, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 1,
                            TeamA = "AEL",
                            TeamB = "OFI"
                        },
                        new
                        {
                            ID = new Guid("2245137d-f773-4e15-beb6-63e33efde74b"),
                            Description = "PAS - IRAKLIS",
                            MatchDate = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 5, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "PAS",
                            TeamB = "IRAKLIS"
                        },
                        new
                        {
                            ID = new Guid("43b2cbea-f255-48de-bc8b-9f57c69b1a74"),
                            Description = "ATROMITOS - OSFP",
                            MatchDate = new DateTime(2023, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 1,
                            TeamA = "ATROMITOS",
                            TeamB = "OSFP"
                        },
                        new
                        {
                            ID = new Guid("0e911fa2-0984-480f-aa0c-f4fe5952c288"),
                            Description = "PAO - AEL",
                            MatchDate = new DateTime(2023, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 7, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "PAO",
                            TeamB = "AEL"
                        },
                        new
                        {
                            ID = new Guid("efb755a6-facf-4c74-a5df-4d5a8c776513"),
                            Description = "ARIS - AEK",
                            MatchDate = new DateTime(2023, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 1,
                            TeamA = "ARIS",
                            TeamB = "AEK"
                        },
                        new
                        {
                            ID = new Guid("bc17ed3f-f331-4b2d-97d6-54508460e773"),
                            Description = "OFI - PAS",
                            MatchDate = new DateTime(2023, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 9, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "OFI",
                            TeamB = "PAS"
                        },
                        new
                        {
                            ID = new Guid("3dc581e4-c4ac-453a-bbdb-96e47ec0f8f5"),
                            Description = "IRAKLIS - ATROMITOS",
                            MatchDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 1,
                            TeamA = "IRAKLIS",
                            TeamB = "ATROMITOS"
                        },
                        new
                        {
                            ID = new Guid("98eddf51-4fcb-43fb-901d-f377c895615a"),
                            Description = "OSFP - PAO",
                            MatchDate = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "OSFP",
                            TeamB = "PAO"
                        },
                        new
                        {
                            ID = new Guid("6816f154-9e2a-46f5-93df-58581e1af7e5"),
                            Description = "AEK - ARIS",
                            MatchDate = new DateTime(2023, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "AEK",
                            TeamB = "ARIS"
                        },
                        new
                        {
                            ID = new Guid("09d63ecd-9b44-4704-9e30-7e8917f86cd9"),
                            Description = "AEL - OFI",
                            MatchDate = new DateTime(2023, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 13, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 1,
                            TeamA = "AEL",
                            TeamB = "OFI"
                        },
                        new
                        {
                            ID = new Guid("388dbe54-27b6-4fdd-8896-eb9481a95ff6"),
                            Description = "PAS - IRAKLIS",
                            MatchDate = new DateTime(2023, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 14, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "PAS",
                            TeamB = "IRAKLIS"
                        },
                        new
                        {
                            ID = new Guid("f99c5691-782c-4474-8e6e-ec3324986d2e"),
                            Description = "ATROMITOS - OSFP",
                            MatchDate = new DateTime(2023, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 15, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 1,
                            TeamA = "ATROMITOS",
                            TeamB = "OSFP"
                        },
                        new
                        {
                            ID = new Guid("faeace46-f6ae-4ca5-8a40-756ccbe739bc"),
                            Description = "PAO - AEL",
                            MatchDate = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 16, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "PAO",
                            TeamB = "AEL"
                        },
                        new
                        {
                            ID = new Guid("0b56834f-f6a8-4f7f-9c06-9ec654c3273b"),
                            Description = "ARIS - AEK",
                            MatchDate = new DateTime(2023, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 17, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 1,
                            TeamA = "ARIS",
                            TeamB = "AEK"
                        },
                        new
                        {
                            ID = new Guid("11292fdc-469c-4b83-a3a6-89714400648f"),
                            Description = "OFI - PAS",
                            MatchDate = new DateTime(2023, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 18, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "OFI",
                            TeamB = "PAS"
                        },
                        new
                        {
                            ID = new Guid("b94fea12-4905-48b4-afdc-cd6ea480b527"),
                            Description = "IRAKLIS - ATROMITOS",
                            MatchDate = new DateTime(2023, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 19, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 1,
                            TeamA = "IRAKLIS",
                            TeamB = "ATROMITOS"
                        },
                        new
                        {
                            ID = new Guid("a842f311-5435-4edd-8c92-f19dd4cb3ad3"),
                            Description = "OSFP - PAO",
                            MatchDate = new DateTime(2023, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MatchTime = new DateTime(2023, 11, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Sport = 2,
                            TeamA = "OSFP",
                            TeamB = "PAO"
                        });
                });

            modelBuilder.Entity("BettingAPI.Models.MatchOdds", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Specifier")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MatchID");

                    b.ToTable("MatchOdds");

                    b.HasData(
                        new
                        {
                            ID = new Guid("0151a1c3-224f-49f6-8320-fb962a40185a"),
                            MatchID = new Guid("1c2d829b-574b-4018-a013-2e495961e5af"),
                            Odd = 1.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("ebe0d5c1-6983-4f08-a7ec-e28661c02a5c"),
                            MatchID = new Guid("1c2d829b-574b-4018-a013-2e495961e5af"),
                            Odd = 3.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("6412e81d-1d65-4240-a476-563f849acbe5"),
                            MatchID = new Guid("1c2d829b-574b-4018-a013-2e495961e5af"),
                            Odd = 2.1m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("56205b3b-a765-4e95-bc55-39e8f1306df7"),
                            MatchID = new Guid("d41a1476-7915-4787-96b0-cd1554897e8e"),
                            Odd = 2.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("8efc0e9c-211c-4abe-8a16-38d0200e48b0"),
                            MatchID = new Guid("d41a1476-7915-4787-96b0-cd1554897e8e"),
                            Odd = 11.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("e88e832f-88ff-45ba-8c14-d762fec142ec"),
                            MatchID = new Guid("d41a1476-7915-4787-96b0-cd1554897e8e"),
                            Odd = 4.1m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("1479255b-5581-4758-a0f6-fac8b350609a"),
                            MatchID = new Guid("a1ed0b7f-bd55-47e3-ac8f-a9cfc084f493"),
                            Odd = 21.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("9a5cf555-c013-40d2-abcf-28179c901bed"),
                            MatchID = new Guid("a1ed0b7f-bd55-47e3-ac8f-a9cfc084f493"),
                            Odd = 14.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("945e526a-b25c-460e-bc97-a408718eb798"),
                            MatchID = new Guid("a1ed0b7f-bd55-47e3-ac8f-a9cfc084f493"),
                            Odd = 10.1m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("dc2cb33a-572b-44ec-a4ac-dc01730a34ff"),
                            MatchID = new Guid("e407ae90-843c-4221-8bcc-4e1174f55d7b"),
                            Odd = 3.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("9c28f914-548a-4708-ab10-32cea4d6995d"),
                            MatchID = new Guid("e407ae90-843c-4221-8bcc-4e1174f55d7b"),
                            Odd = 6.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("bb86e5e4-369e-40ea-9d09-17466e02613d"),
                            MatchID = new Guid("e407ae90-843c-4221-8bcc-4e1174f55d7b"),
                            Odd = 5.0m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("b77f498f-fb66-4d06-ab75-64f1054edb53"),
                            MatchID = new Guid("2245137d-f773-4e15-beb6-63e33efde74b"),
                            Odd = 9.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("9acdbd57-99a2-4adc-97ac-812139c84ea2"),
                            MatchID = new Guid("2245137d-f773-4e15-beb6-63e33efde74b"),
                            Odd = 12.0m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("3ec52597-b870-452c-b0bf-f394695196da"),
                            MatchID = new Guid("2245137d-f773-4e15-beb6-63e33efde74b"),
                            Odd = 15.0m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("c6c6cddb-c380-45a7-ad82-e6a651923825"),
                            MatchID = new Guid("43b2cbea-f255-48de-bc8b-9f57c69b1a74"),
                            Odd = 4.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("564d081d-5757-458c-ac87-e3fcd006a5d3"),
                            MatchID = new Guid("43b2cbea-f255-48de-bc8b-9f57c69b1a74"),
                            Odd = 2.8m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("642797a3-aebc-4f18-8361-0306379da16d"),
                            MatchID = new Guid("43b2cbea-f255-48de-bc8b-9f57c69b1a74"),
                            Odd = 1.9m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("66e40d2c-828c-437b-9e35-d8d42a5c6fb0"),
                            MatchID = new Guid("0e911fa2-0984-480f-aa0c-f4fe5952c288"),
                            Odd = 3.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("c6abcbad-3388-4b2c-9a7d-573c670fe076"),
                            MatchID = new Guid("0e911fa2-0984-480f-aa0c-f4fe5952c288"),
                            Odd = 4.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("cdbaed02-3be1-43f4-83e3-e708ab252fe9"),
                            MatchID = new Guid("0e911fa2-0984-480f-aa0c-f4fe5952c288"),
                            Odd = 2.1m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("fc99b406-4350-4331-a8c5-404a13779b4e"),
                            MatchID = new Guid("efb755a6-facf-4c74-a5df-4d5a8c776513"),
                            Odd = 2.3m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("3098d611-a6a3-4bf4-9af0-4f0fcc664f71"),
                            MatchID = new Guid("efb755a6-facf-4c74-a5df-4d5a8c776513"),
                            Odd = 5.7m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("b8d92d07-3a81-454b-b845-48cea35d626a"),
                            MatchID = new Guid("efb755a6-facf-4c74-a5df-4d5a8c776513"),
                            Odd = 3.2m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("5011bad6-afe4-4185-bf79-4b74d720b531"),
                            MatchID = new Guid("bc17ed3f-f331-4b2d-97d6-54508460e773"),
                            Odd = 1.8m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("72466db3-0ba1-4cb9-adcd-d034e3f0c347"),
                            MatchID = new Guid("bc17ed3f-f331-4b2d-97d6-54508460e773"),
                            Odd = 2.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("4f221313-0336-4638-85e2-e98aec58db3d"),
                            MatchID = new Guid("bc17ed3f-f331-4b2d-97d6-54508460e773"),
                            Odd = 3.5m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("34ff33b0-0512-46df-948f-a35f765aa79e"),
                            MatchID = new Guid("3dc581e4-c4ac-453a-bbdb-96e47ec0f8f5"),
                            Odd = 2.1m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("39f5eb58-4593-4702-bf73-321532e02283"),
                            MatchID = new Guid("3dc581e4-c4ac-453a-bbdb-96e47ec0f8f5"),
                            Odd = 6.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("3bd6b4dd-54b8-4b67-950a-66d39a8e43e6"),
                            MatchID = new Guid("3dc581e4-c4ac-453a-bbdb-96e47ec0f8f5"),
                            Odd = 4.3m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("db692d51-91c3-4f06-b95a-56d7830ebc1f"),
                            MatchID = new Guid("98eddf51-4fcb-43fb-901d-f377c895615a"),
                            Odd = 3.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("ee7874ee-1523-498c-ae85-1ac81eb020df"),
                            MatchID = new Guid("98eddf51-4fcb-43fb-901d-f377c895615a"),
                            Odd = 7.1m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("b3eff906-ec60-4e68-a571-3ec13dd19dc0"),
                            MatchID = new Guid("98eddf51-4fcb-43fb-901d-f377c895615a"),
                            Odd = 2.9m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("bf3af53b-a579-4292-b98e-dabb380ef5dd"),
                            MatchID = new Guid("6816f154-9e2a-46f5-93df-58581e1af7e5"),
                            Odd = 1.9m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("cbdcd566-e18c-45e3-a1aa-2154cf279aec"),
                            MatchID = new Guid("6816f154-9e2a-46f5-93df-58581e1af7e5"),
                            Odd = 4.3m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("31a31beb-1952-4c76-9407-29526196268d"),
                            MatchID = new Guid("6816f154-9e2a-46f5-93df-58581e1af7e5"),
                            Odd = 2.5m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("96062e2b-7117-460a-ba1a-a994175837b7"),
                            MatchID = new Guid("09d63ecd-9b44-4704-9e30-7e8917f86cd9"),
                            Odd = 2.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("468e17e0-954a-463e-82cd-1e8544ab862e"),
                            MatchID = new Guid("09d63ecd-9b44-4704-9e30-7e8917f86cd9"),
                            Odd = 1.8m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("fc221c13-96b4-4f23-876d-b54fcfb3cdf8"),
                            MatchID = new Guid("09d63ecd-9b44-4704-9e30-7e8917f86cd9"),
                            Odd = 4.0m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("cf2a6b8b-7f78-4c37-a70d-22723456298d"),
                            MatchID = new Guid("388dbe54-27b6-4fdd-8896-eb9481a95ff6"),
                            Odd = 3.2m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("c8299be9-c99c-4a58-afc1-81ea7177af66"),
                            MatchID = new Guid("388dbe54-27b6-4fdd-8896-eb9481a95ff6"),
                            Odd = 2.1m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("b2ad695c-10b4-42ba-8f14-49994acff6f4"),
                            MatchID = new Guid("388dbe54-27b6-4fdd-8896-eb9481a95ff6"),
                            Odd = 1.5m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("5e530860-cafa-460e-9a58-bb4f56378150"),
                            MatchID = new Guid("f99c5691-782c-4474-8e6e-ec3324986d2e"),
                            Odd = 2.8m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("8059b378-4877-4a67-8b77-87030e58b416"),
                            MatchID = new Guid("f99c5691-782c-4474-8e6e-ec3324986d2e"),
                            Odd = 1.9m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("3dcd3315-a7c2-4b88-b5a1-b84de847c336"),
                            MatchID = new Guid("f99c5691-782c-4474-8e6e-ec3324986d2e"),
                            Odd = 4.5m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("6ee491ae-e8f5-4229-b5f0-96e162ff3093"),
                            MatchID = new Guid("faeace46-f6ae-4ca5-8a40-756ccbe739bc"),
                            Odd = 4.2m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("95a69baf-1885-4c4f-af88-605f6ade5ee2"),
                            MatchID = new Guid("faeace46-f6ae-4ca5-8a40-756ccbe739bc"),
                            Odd = 2.1m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("30287165-9956-4c56-be7f-4964595afef4"),
                            MatchID = new Guid("faeace46-f6ae-4ca5-8a40-756ccbe739bc"),
                            Odd = 3.5m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("9773ab24-86a1-4fe3-bb68-30bd17502164"),
                            MatchID = new Guid("0b56834f-f6a8-4f7f-9c06-9ec654c3273b"),
                            Odd = 5.7m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("9bfd4ff8-76bb-4fc9-b13e-199803806dfa"),
                            MatchID = new Guid("0b56834f-f6a8-4f7f-9c06-9ec654c3273b"),
                            Odd = 3.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("bb2f2de5-989a-42fd-936f-d1da583653b1"),
                            MatchID = new Guid("0b56834f-f6a8-4f7f-9c06-9ec654c3273b"),
                            Odd = 2.3m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("db15a8d0-6857-42c5-a1a0-a75155935f96"),
                            MatchID = new Guid("11292fdc-469c-4b83-a3a6-89714400648f"),
                            Odd = 2.2m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("7a993817-976c-4abf-b271-854b32980a2e"),
                            MatchID = new Guid("11292fdc-469c-4b83-a3a6-89714400648f"),
                            Odd = 3.5m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("bc99e591-61e7-4655-93b2-495ea68b6662"),
                            MatchID = new Guid("11292fdc-469c-4b83-a3a6-89714400648f"),
                            Odd = 1.8m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("7c28036d-8879-440e-99b7-7e99fde2183f"),
                            MatchID = new Guid("b94fea12-4905-48b4-afdc-cd6ea480b527"),
                            Odd = 6.2m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("c4afcb79-a7ea-48c8-9959-65dd785b98ff"),
                            MatchID = new Guid("b94fea12-4905-48b4-afdc-cd6ea480b527"),
                            Odd = 4.3m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("fa9b5071-8644-4f06-8b9e-3ac8896e5d64"),
                            MatchID = new Guid("b94fea12-4905-48b4-afdc-cd6ea480b527"),
                            Odd = 2.1m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("f4647e4e-6810-42cc-924a-92f77d11aa96"),
                            MatchID = new Guid("a842f311-5435-4edd-8c92-f19dd4cb3ad3"),
                            Odd = 7.1m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("8f75c42a-60fc-4d01-93f7-5bc8fa1d41d7"),
                            MatchID = new Guid("a842f311-5435-4edd-8c92-f19dd4cb3ad3"),
                            Odd = 2.9m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("b80ff5fe-8009-47b1-9207-c508662dec30"),
                            MatchID = new Guid("a842f311-5435-4edd-8c92-f19dd4cb3ad3"),
                            Odd = 3.5m,
                            Specifier = 2
                        });
                });

            modelBuilder.Entity("BettingAPI.Models.MatchOdds", b =>
                {
                    b.HasOne("BettingAPI.Models.Match", "Match")
                        .WithMany("MatchOdds")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BettingAPI.Models.Match", b =>
                {
                    b.Navigation("MatchOdds");
                });
#pragma warning restore 612, 618
        }
    }
}
