// <auto-generated />
using System;
using BettingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BettingAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231110162049_Seeder")]
    partial class Seeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BettingAPI.Models.Match", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MatchTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sport")
                        .HasColumnType("int");

                    b.Property<string>("TeamA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Match");

                    b.HasData(
                        new
                        {
                            ID = new Guid("12f961ed-7e67-4ee1-baae-d3d9fbdc57b0"),
                            Description = "OSFP - PAO",
                            MatchDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            MatchTime = new DateTime(2023, 11, 10, 18, 20, 49, 715, DateTimeKind.Local).AddTicks(8538),
                            Sport = 1,
                            TeamA = "OSFP",
                            TeamB = "PAO"
                        },
                        new
                        {
                            ID = new Guid("58910587-eeb2-4d3f-8cd1-f57e084c5c93"),
                            Description = "OSFP - PAO",
                            MatchDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            MatchTime = new DateTime(2023, 11, 10, 18, 20, 49, 715, DateTimeKind.Local).AddTicks(8541),
                            Sport = 2,
                            TeamA = "OSFP",
                            TeamB = "PAO"
                        },
                        new
                        {
                            ID = new Guid("9f901ef4-3878-4b20-8b0a-f3c4717b6524"),
                            Description = "AEK - ARIS",
                            MatchDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            MatchTime = new DateTime(2023, 11, 10, 18, 20, 49, 715, DateTimeKind.Local).AddTicks(8547),
                            Sport = 2,
                            TeamA = "AEK",
                            TeamB = "ARIS"
                        });
                });

            modelBuilder.Entity("BettingAPI.Models.MatchOdds", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MatchID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Odd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Specifier")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MatchID");

                    b.ToTable("MatchOdds");

                    b.HasData(
                        new
                        {
                            ID = new Guid("bc5c91b7-f042-4f5e-99d6-e5a5572105e1"),
                            MatchID = new Guid("12f961ed-7e67-4ee1-baae-d3d9fbdc57b0"),
                            Odd = 1.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("8d778844-59dd-4598-a0e7-54344e1d23bb"),
                            MatchID = new Guid("12f961ed-7e67-4ee1-baae-d3d9fbdc57b0"),
                            Odd = 3.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("749eba9a-b05c-4e39-81bc-b7429cfb035e"),
                            MatchID = new Guid("12f961ed-7e67-4ee1-baae-d3d9fbdc57b0"),
                            Odd = 2.1m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("010c0c20-989f-4047-98e5-aa81670e882c"),
                            MatchID = new Guid("58910587-eeb2-4d3f-8cd1-f57e084c5c93"),
                            Odd = 2.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("0aa64f8e-2490-4443-90ab-99a7b67ba57d"),
                            MatchID = new Guid("58910587-eeb2-4d3f-8cd1-f57e084c5c93"),
                            Odd = 11.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("8193092d-42ff-419f-83e8-d15b187df1ec"),
                            MatchID = new Guid("58910587-eeb2-4d3f-8cd1-f57e084c5c93"),
                            Odd = 4.1m,
                            Specifier = 2
                        },
                        new
                        {
                            ID = new Guid("f212fb32-204f-429a-962a-1c5f9ea4a4db"),
                            MatchID = new Guid("9f901ef4-3878-4b20-8b0a-f3c4717b6524"),
                            Odd = 21.5m,
                            Specifier = 1
                        },
                        new
                        {
                            ID = new Guid("683d4cd0-82ae-4cc1-bc23-308cca81c776"),
                            MatchID = new Guid("9f901ef4-3878-4b20-8b0a-f3c4717b6524"),
                            Odd = 14.2m,
                            Specifier = 3
                        },
                        new
                        {
                            ID = new Guid("135a728a-e39f-4cad-8a1e-7665b944b2ec"),
                            MatchID = new Guid("9f901ef4-3878-4b20-8b0a-f3c4717b6524"),
                            Odd = 10.1m,
                            Specifier = 2
                        });
                });

            modelBuilder.Entity("BettingAPI.Models.MatchOdds", b =>
                {
                    b.HasOne("BettingAPI.Models.Match", "Match")
                        .WithMany("MatchOdds")
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BettingAPI.Models.Match", b =>
                {
                    b.Navigation("MatchOdds");
                });
#pragma warning restore 612, 618
        }
    }
}
